apiVersion: v2
description: A library chart for reuse in other charts
name: common
type: library
version: 0.1.0
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 2.x.x
    tags:
      - bitnami-common
